steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-operator'
  args: [
    'build',
    '-f', 'Dockerfile.operator',
    '-t', 'gcr.io/$PROJECT_ID/wireguard-operator:latest',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-wireguard'
  args: [
    'build',
    '-f', 'Dockerfile.wireguard',
    '-t', 'gcr.io/$PROJECT_ID/wireguard:latest',
    '.'
  ]
  waitFor: '-'
images:
  - 'gcr.io/$PROJECT_ID/wireguard-operator:latest'
  - 'gcr.io/$PROJECT_ID/wireguard:latest'
